language: python
python: "3.6"
addons:
  postgresql: "9.6"
env:
    - DJANGO_SETTINGS_MODULE=config.settings.test
install:
    - pip install wheel
    - pip install -r requirements.txt
    - pip install coveralls
before_script:
    - psql -U postgres -c "CREATE USER modeemintternet WITH PASSWORD 'modeemintternet';"
    - psql -U postgres -c "ALTER USER modeemintternet CREATEDB;"
    - psql -U postgres -c "CREATE DATABASE modeemintternet ENCODING 'UTF8' OWNER modeemintternet;"
    - psql -U postgres -c "CREATE DATABASE modeemiuserdb ENCODING 'UTF8' OWNER modeemintternet;"
script:
    - python manage.py migrate
    - coverage run --source=modeemintternet manage.py test
after_success:
    - coveralls
