dist: xenial
language: python
cache: pip
python:
  - 3.7
addons:
  postgresql: 9.6
install:
  - pip install tox-travis codecov
before_script:
  - psql -U postgres -c "CREATE USER modeemintternet WITH PASSWORD 'modeemintternet';"
  - psql -U postgres -c "ALTER USER modeemintternet CREATEDB;"
  - psql -U postgres -c "CREATE DATABASE modeemintternet ENCODING 'UTF8' OWNER modeemintternet;"
  - psql -U postgres -c "CREATE DATABASE modeemiuserdb ENCODING 'UTF8' OWNER modeemintternet;"
script:
  - tox
after_success:
  - codecov
