name: Website CI

on: [push, pull_request]

jobs:
  tox:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/free-pro-team@latest/actions/guides/creating-postgresql-service-containers
    container: python:3.8
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox tox-gh-actions

    - name: Tox tests
      run: |
        tox -v
      env:
        DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"

    - name: Upload coverage
      uses: codecov/codecov-action@v1
